export * from "./class";
export * from "./dashboard";
export * from "./first";
export * from "./frequency";
export * from "./login";
export * from "./report";
export * from "./school";
export * from "./student";
export * from "./user";
